### ISSUE TITLE
Starting brand new install of tC, exit, and start again throws can't read currentPaneSettings error

### ISSUE THREAD

**Issue by richmahn** [unfoldingWord/translationCore#4084]
If you start tC as a brand new install and then don't visit a tool that loads the ScripturePane and exit, and then start it up again, you get an error of currentPaneSettings  property not being readable. Need to set some defaults:
```
Uncaught TypeError: Cannot read property 'currentPaneSettings' of undefined
    at C:/repos/translationCore/src/js/actions/SettingsMigrationActions.js:31:33
    at C:\repos\translationCore\node_modules\redux-thunk\lib\index.js:11:18
    at dispatch (C:\repos\translationCore\node_modules\redux\lib\applyMiddleware.js:45:18)
    at C:/repos/translationCore/src/js/actions/SettingsMigrationActions.js:17:7
    at C:\repos\translationCore\node_modules\redux-thunk\lib\index.js:11:18
    at Object.migrateToolsSettings (C:/repos/translationCore/src/js/pages/app.js:109:9)
    at Main.componentDidMount (C:/repos/translationCore/src/js/pages/app.js:51:24)
    at commitLifeCycles (C:\repos\translationCore\node_modules\react-dom\cjs\react-dom.development.js:8770:24)
    at commitAllLifeCycles (C:\repos\translationCore\node_modules\react-dom\cjs\react-dom.development.js:9946:9)
    at HTMLUnknownElement.callCallback (C:\repos\translationCore\node_modules\react-dom\cjs\react-dom.development.js:542:14)
```

**Comment by mannycolon** [comment]
@richmahn close this issue. i got it fixed in my PR now

**Comment by richmahn** [comment]
Manny fixed.
