### ISSUE TITLE
macOS build consistently fails on new Github Actions.

### ISSUE THREAD

**Issue by da1nerd** [unfoldingWord/translationCore#6648]
```
[10:10:15] 'build_binaries' errored after 40 s
[10:10:15] Error: Error: Command failed: npm prune --production
npm WARN wordmap@0.4.3 requires a peer of wordmap-lexer@0.3.4 but none is installed. You must install peer dependencies yourself.

npm ERR! invalid bin entry for package electron-download@4.1.1. key=electron-download, value=lib/cli.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2020-01-16T10_10_15_945Z-debug.log

    at packager (/__w/translationCore/translationCore/gulpfile.js:173:13)
    at /__w/translationCore/translationCore/node_modules/electron-packager/index.js:165:23
    at end (/__w/translationCore/translationCore/node_modules/run-series/index.js:10:15)
    at done (/__w/translationCore/translationCore/node_modules/run-series/index.js:13:10)
    at each (/__w/translationCore/translationCore/node_modules/run-series/index.js:18:43)
    at buildMacApp (/__w/translationCore/translationCore/node_modules/electron-packager/mac.js:257:23)
    at /__w/translationCore/translationCore/node_modules/electron-packager/common.js:286:23
    at end (/__w/translationCore/translationCore/node_modules/run-series/index.js:10:15)
    at done (/__w/translationCore/translationCore/node_modules/run-series/index.js:13:10)
    at each (/__w/translationCore/translationCore/node_modules/run-series/index.js:18:43)
    at ChildProcess.exithandler (child_process.js:288:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[10:10:15] 'build' errored after 40 s
##[error]Process completed with exit code 1.
```
See for example https://github.com/unfoldingWord/translationCore/runs/382578484

**Comment by da1nerd** [comment]
As a temporary fix I'm running the mac builds on the linux environment. The downside is the generated artifacts will be a bit larger since linux can't do the same dmg compression as macos.

**Comment by da1nerd** [comment]
Switching to a linux environment didn't fix the issue. So there must be a dependency somewhere that changed.

**Comment by PhotoNomad0** [comment]
Looking good now
