### ISSUE TITLE
Adjust tC build process to electronite

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#6726]
We need to adjust the tCore build scripts to work with the `sandbox-electronite` branch.

**Note:** this is for **building** only, unit tests are a separate issue.

**Current State:**
If I add the script back into package.json `"release-osx": "npm i && gulp clean && npm i && npm run load-apps && gulp build --osx && gulp release --osx",` I get the following error:

```
[08:29:01] Using gulpfile ~/Development/Electron/translationCore/gulpfile.js
[08:29:01] Starting 'build'...
[08:29:01] Starting 'set_mode'...
Skipping build mode. On non-travis environment
[08:29:01] Finished 'set_mode' after 1.31 ms
[08:29:01] Starting 'build_binaries'...
	(Ignoring)	 /vendor
	(Ignoring)	 /scripts
	(Ignoring)	 /node_modules/yargs-parser/package.json

...

	(Ignoring)	 /.gitignore
	(Ignoring)	 /.github
	(Ignoring)	 /.git
	(Ignoring)	 /.eslintrc.json
	(Ignoring)	 /.editorconfig
	(Ignoring)	 /.concourse
	(Ignoring)	 /.codecov.yml
[08:30:44] The following tasks did not complete: build, build_binaries
[08:30:44] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! translationCore@2.2.0 release-osx: `npm i && gulp clean && npm i && npm run load-apps && gulp build --osx && gulp release --osx`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the translationCore@2.2.0 release-osx script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/blm/.npm/_logs/2020-03-13T12_30_44_508Z-debug.log
```

**Comment by da1nerd** [comment]
fyi I'm currently working on an `electronite-packager` that will replace our use of `electron-packager`. So there might need to be a dependency link with issue #6661

**Comment by PhotoNomad0** [comment]
@neutrinog - I tried doing build using new script `npm run build` (see sandbox-electronite branch) and it failed with javascript out of heap memory.  Then I ran again after setting environment variable: `export NODE_OPTIONS=--max-old-space-size=4096` and it completed creating a translationCore.app.  When I ran this app I got an error:
```
Uncaught Exception:
Error: Cannot find module 'dotenv'
Require stack:
- /Users/blm/Development/Electron/translationCore/dist/translationCore-darwin-x64/translationCore.app/Contents/Resources/app/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (/Users/blm/Development/Electron/translationCore/dist/translationCore-darwin-x64/translationCore.app/Contents/Resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/blm/Development/Electron/translationCore/dist/translationCore-darwin-x64/translationCore.app/Contents/Resources/app/main.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
```

It looks like we might be quite close.

**Comment by da1nerd** [comment]
This is the same thing that's currently blocking me from finishing #6661.
We need to get main.js to be processed by webpack in order for it to pull in all of the dependencies. See https://github.com/unfoldingWord/translationCore/issues/6661#issuecomment-600595316 it's the same error, just different module since I'm using a bare project template.

I'm not sure what's up with your heap memory though. Probably something to do with webpack running out of memory while looking through dependencies. I'm not certain if we should be concerned about it though, because webpack should be compiling things down to tidy chunks for us and hopefully doing treeshaking.

**Comment by cckozie** [comment]
Testing is blocked until we are able to render complex scripts.
