### ISSUE TITLE
Get unit tests running

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#6729]
Currently see error running tests (see below).  Maybe a configuration issue in the craco environment?
```
translationCore % npm test

> translationCore@2.1.0 test /Users/blm/Development/Electron/translationCore
> craco test

TypeError: fsevents is not a function
    at new FSEventsWatcher (/Users/blm/Development/Electron/translationCore/node_modules/jest-haste-map/build/lib/FSEventsWatcher.js:162:20)
    at createWatcher (/Users/blm/Development/Electron/translationCore/node_modules/jest-haste-map/build/index.js:1052:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/blm/Development/Electron/translationCore/node_modules/jest-haste-map/build/index.js:1230:44)
    at /Users/blm/Development/Electron/translationCore/node_modules/jest-haste-map/build/index.js:517:21
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/blm/Development/Electron/translationCore/node_modules/jest-haste-map/build/index.js:193:24)
    at _next (/Users/blm/Development/Electron/translationCore/node_modules/jest-haste-map/build/index.js:213:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
npm ERR! Test failed.  See above for more details.

```

**Comment by PhotoNomad0** [comment]
Found a thread that may be helpful: https://github.com/facebook/create-react-app/issues/6891

a couple of work-arounds suggested including switching to installing npm packages using yarn which makes sense, since react create uses yarn.

Versions:
electron 6.0.7
chrome 76.0.3809.139
node 12.4.0

**Comment by PhotoNomad0** [comment]
Tried:
```
rm -rf node_modules
rm -f yarn.lock 
yarn
```
 and got error:
```
error cross-env@7.0.0: The engine "node" is incompatible with this module. Expected version ">=10.14".
error Found incompatible module
```
 Currently have node: v8.16.1

Installed same node version as electron 6.0.7:
```
Node.js v12.4.0 to /usr/local/bin/node
npm v6.9.0 to /usr/local/bin/npm
```

**Comment by PhotoNomad0** [comment]
Now can run unit tests. To set up, need to first install Node.js v12.4.0 and then do:
```
rm -rf node_modules
rm -f yarn.lock 
yarn
```

`yarn` takes the place of `npm i`.

Now can run unit tests by doing `yarn test`

Note: currently have yarn v1.9.4 on PC

**Comment by PhotoNomad0** [comment]
Unfortunately now the app will throw errors when I try to do npm start:
```
translationCore % npm start

> translationCore@2.1.0 start /Users/blm/Development/Electron/translationCore
> concurrently "yarn react-start" "wait-on http://localhost:3000/ && cross-env NODE_ENV=development yarn electron-start"

yarn run v1.9.4
$ craco start
[0] ℹ ｢wds｣: Project is running at http://192.168.142.56/
[0] ℹ ｢wds｣: webpack output is served from /
[0] ℹ ｢wds｣: Content not from webpack is served from /Users/blm/Development/Electron/translationCore/public
[0] ℹ ｢wds｣: 404s will fallback to /index.html
[0] Starting the development server...
[0] 
[0] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
[0]     at validateString (internal/validators.js:107:11)
[0]     at Object.join (path.js:1037:7)
[0]     at noopServiceWorkerMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:317:13)
[0]     at /Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:275:10)
[0]     at launchEditorMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
[0]     at validateString (internal/validators.js:107:11)
[0]     at Object.join (path.js:1037:7)
[0]     at noopServiceWorkerMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:317:13)
[0]     at /Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:275:10)
[0]     at launchEditorMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
[0]     at validateString (internal/validators.js:107:11)
[0]     at Object.join (path.js:1037:7)
[0]     at noopServiceWorkerMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:317:13)
[0]     at /Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:275:10)
[0]     at launchEditorMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
[0]     at validateString (internal/validators.js:107:11)
[0]     at Object.join (path.js:1037:7)
[0]     at noopServiceWorkerMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:317:13)
[0]     at /Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:275:10)
[0]     at launchEditorMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
[0]     at validateString (internal/validators.js:107:11)
[0]     at Object.join (path.js:1037:7)
[0]     at noopServiceWorkerMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:317:13)
[0]     at /Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:275:10)
[0]     at launchEditorMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
[0]     at validateString (internal/validators.js:107:11)
[0]     at Object.join (path.js:1037:7)
[0]     at noopServiceWorkerMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:317:13)
[0]     at /Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:275:10)
[0]     at launchEditorMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
[0]     at validateString (internal/validators.js:107:11)
[0]     at Object.join (path.js:1037:7)
[0]     at noopServiceWorkerMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:317:13)
[0]     at /Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:275:10)
[0]     at launchEditorMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
[0]     at validateString (internal/validators.js:107:11)
[0]     at Object.join (path.js:1037:7)
[0]     at noopServiceWorkerMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:317:13)
[0]     at /Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:275:10)
[0]     at launchEditorMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
[0]     at validateString (internal/validators.js:107:11)
[0]     at Object.join (path.js:1037:7)
[0]     at noopServiceWorkerMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:317:13)
[0]     at /Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:275:10)
[0]     at launchEditorMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
[0]     at validateString (internal/validators.js:107:11)
[0]     at Object.join (path.js:1037:7)
[0]     at noopServiceWorkerMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:317:13)
[0]     at /Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:275:10)
[0]     at launchEditorMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
[0]     at validateString (internal/validators.js:107:11)
[0]     at Object.join (path.js:1037:7)
[0]     at noopServiceWorkerMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:317:13)
[0]     at /Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:275:10)
[0]     at launchEditorMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
[0]     at validateString (internal/validators.js:107:11)
[0]     at Object.join (path.js:1037:7)
[0]     at noopServiceWorkerMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:317:13)
[0]     at /Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:275:10)
[0]     at launchEditorMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
[0]     at validateString (internal/validators.js:107:11)
[0]     at Object.join (path.js:1037:7)
[0]     at noopServiceWorkerMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:317:13)
[0]     at /Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:275:10)
[0]     at launchEditorMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
[0]     at validateString (internal/validators.js:107:11)
[0]     at Object.join (path.js:1037:7)
[0]     at noopServiceWorkerMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:317:13)
[0]     at /Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:275:10)
[0]     at launchEditorMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
[0]     at validateString (internal/validators.js:107:11)
[0]     at Object.join (path.js:1037:7)
[0]     at noopServiceWorkerMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:317:13)
[0]     at /Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:275:10)
[0]     at launchEditorMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
^C[1] wait-on http://localhost:3000/ && cross-env NODE_ENV=development yarn electron-start exited with code SIGINT
[0] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
[0]     at validateString (internal/validators.js:107:11)
[0]     at Object.join (path.js:1037:7)
[0]     at noopServiceWorkerMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:317:13)
[0]     at /Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/index.js:275:10)
[0]     at launchEditorMiddleware (/Users/blm/Development/Electron/translationCore/node_modules/react-scripts/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
[0]     at Layer.handle [as handle_request] (/Users/blm/Development/Electron/translationCore/node_modules/express/lib/router/layer.js:95:5)
[0] yarn react-start exited with code SIGINT
blm@MacBook-Pro-2 translationCore % 

```

**Comment by PhotoNomad0** [comment]
Upgraded to `react-scripts@3.4.0` and no longer seeing the errors on yarn start, but now seeing tCore start to empty screen - nothing is running.

**Comment by PhotoNomad0** [comment]
Tried various node versions on PC
- node-v11.15.0 & cross-env@7.0.2 - no Tc, yarn tests run.
- node-v8.16.1 & cross-env@v6.0.3 & react-scripts@3.3.1 - no longer runs. turned out package-lock.json was missing an entry.  Now have running again when I reset package.json and package-lock.json to original and do npm ci (looks like packages are being automatically promoted that cause breakage).
  - was able to get unit tests to work by deleting fsevents from node_modules - looks like it is pulled in by react-scripts.
  - if I upgrade to react-scripts@3.4.0 tCore breaks (looks like packages are being automatically promoted that cause breakage).

**Comment by PhotoNomad0** [comment]
~**Note:** for now, found a test work-around to get unit tests to run:  stick with using `npm ci` to install packages and then delete fsevents from node_modules - looks like it is pulled in by react-scripts.~

**Comment by mannycolon** [comment]
Notes:

- https://www.npmjs.com/package/@craco/craco
- https://medium.com/@andrew.rapo/using-create-react-app-craco-to-build-apps-for-both-the-web-and-electron-8f4ab827877f
- https://dev.to/loribbaum/converting-a-create-react-app-using-craco-to-typescript-53b0
